export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_IN_CART = 'DELETE_IN_CART';
export const UPDATE_IN_CART = 'UPDATE_IN_CART';
export const CHANGE_MESSAGE_DELETE = 'CHANGE_MESSAGE_DELETE';



